steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/capstone-agentic-ai-frontend:$COMMIT_SHA"
      - --build-arg
      - NEXT_PUBLIC_API_URL=https://capstone-agentic-ai-backend-3j5mi36wwa-uc.a.run.app
      - frontend/

  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/$PROJECT_ID/capstone-agentic-ai-frontend:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - deploy
      - capstone-agentic-ai-frontend
      - --image=gcr.io/$PROJECT_ID/capstone-agentic-ai-frontend:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=1Gi
      - --timeout=300

images:
  - "gcr.io/$PROJECT_ID/capstone-agentic-ai-frontend:$COMMIT_SHA"